-- seed_valentina_data.sql
-- Généré automatiquement

-- Nettoyage
TRUNCATE public.skill_compatibility CASCADE;
TRUNCATE public.skills CASCADE;

-- Insertion des compétences
INSERT INTO public.skills (name, territory, element, energy, sub_energy, pure_score) VALUES ('Créativité', 'Calyxis', 'Feu', 'CRÉATION', 'CRÉER', 0.0);
INSERT INTO public.skills (name, territory, element, energy, sub_energy, pure_score) VALUES ('Innovation', 'Calyxis', 'Feu', 'CRÉATION', 'CRÉER', 0.0);
INSERT INTO public.skills (name, territory, element, energy, sub_energy, pure_score) VALUES ('Imagination', 'Calyxis', 'Feu', 'CRÉATION', 'CRÉER', 0.0);
INSERT INTO public.skills (name, territory, element, energy, sub_energy, pure_score) VALUES ('Initiative', 'Calyxis', 'Feu', 'ACTION', 'AGIR', 0.0);
INSERT INTO public.skills (name, territory, element, energy, sub_energy, pure_score) VALUES ('Persévérance', 'Calyxis', 'Feu', 'ACTION', 'AGIR', 0.0);
INSERT INTO public.skills (name, territory, element, energy, sub_energy, pure_score) VALUES ('Pitch', 'Sylvara', 'Terre', 'COOPERATION_COMMUNICATION', 'COMMUNIQUER', 0.0);
INSERT INTO public.skills (name, territory, element, energy, sub_energy, pure_score) VALUES ('Prise de parole', 'Sylvara', 'Terre', 'COOPERATION_COMMUNICATION', 'COMMUNIQUER', 0.0);
INSERT INTO public.skills (name, territory, element, energy, sub_energy, pure_score) VALUES ('Argumentation', 'Sylvara', 'Terre', 'COOPERATION_COMMUNICATION', 'COMMUNIQUER', 0.0);
INSERT INTO public.skills (name, territory, element, energy, sub_energy, pure_score) VALUES ('Analyse', 'Sylvara', 'Terre', 'ACTION', 'RÉSOUDRE', 0.0);
INSERT INTO public.skills (name, territory, element, energy, sub_energy, pure_score) VALUES ('Esprit critique', 'Sylvara', 'Terre', 'ACTION', 'RÉSOUDRE', 0.0);
INSERT INTO public.skills (name, territory, element, energy, sub_energy, pure_score) VALUES ('Organisation', 'Cattleya', 'Air', 'CRÉATION', 'PILOTER', 0.0);
INSERT INTO public.skills (name, territory, element, energy, sub_energy, pure_score) VALUES ('Gestion de projet', 'Cattleya', 'Air', 'CRÉATION', 'PILOTER', 0.0);
INSERT INTO public.skills (name, territory, element, energy, sub_energy, pure_score) VALUES ('Leadership', 'Cattleya', 'Air', 'CRÉATION', 'PILOTER', 0.0);
INSERT INTO public.skills (name, territory, element, energy, sub_energy, pure_score) VALUES ('Résolution de problèmes', 'Cattleya', 'Air', 'ACTION', 'RÉSOUDRE', 0.0);
INSERT INTO public.skills (name, territory, element, energy, sub_energy, pure_score) VALUES ('Travail d''équipe', 'Neptunus', 'Eau', 'COOPERATION_COMMUNICATION', 'COOPÉRER', 0.0);
INSERT INTO public.skills (name, territory, element, energy, sub_energy, pure_score) VALUES ('Écoute', 'Neptunus', 'Eau', 'COOPERATION_COMMUNICATION', 'COOPÉRER', 0.0);
INSERT INTO public.skills (name, territory, element, energy, sub_energy, pure_score) VALUES ('Contribution', 'Neptunus', 'Eau', 'COOPERATION_COMMUNICATION', 'COOPÉRER', 0.0);
INSERT INTO public.skills (name, territory, element, energy, sub_energy, pure_score) VALUES ('Autonomie', 'Neptunus', 'Eau', 'ACTION', 'AGIR', 0.0);

-- Insertion de la compatibilité
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Imagination'), (SELECT id FROM public.skills WHERE name = 'Créativité'), 8.0, 10.0, 9.0, 8.0, 8.9);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Imagination'), (SELECT id FROM public.skills WHERE name = 'Innovation'), 8.0, 9.0, 9.0, 8.0, 8.6);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Imagination'), (SELECT id FROM public.skills WHERE name = 'Initiative'), 4.0, 5.0, 6.0, 7.0, 5.1);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Imagination'), (SELECT id FROM public.skills WHERE name = 'Persévérance'), 3.0, 5.0, 5.0, 6.0, 4.4);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Créativité'), (SELECT id FROM public.skills WHERE name = 'Imagination'), 2.0, 5.0, 4.0, 6.0, 3.9);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Créativité'), (SELECT id FROM public.skills WHERE name = 'Innovation'), 9.0, 9.0, 8.0, 8.0, 8.7);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Créativité'), (SELECT id FROM public.skills WHERE name = 'Initiative'), 5.0, 6.0, 7.0, 7.0, 6.0);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Créativité'), (SELECT id FROM public.skills WHERE name = 'Persévérance'), 4.0, 5.0, 6.0, 7.0, 5.1);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Innovation'), (SELECT id FROM public.skills WHERE name = 'Imagination'), 1.0, 4.0, 3.0, 7.0, 3.1);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Innovation'), (SELECT id FROM public.skills WHERE name = 'Créativité'), 4.0, 6.0, 5.0, 5.0, 5.0);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Innovation'), (SELECT id FROM public.skills WHERE name = 'Initiative'), 8.0, 8.0, 8.0, 7.0, 7.9);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Innovation'), (SELECT id FROM public.skills WHERE name = 'Persévérance'), 7.0, 8.0, 7.0, 8.0, 7.5);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Initiative'), (SELECT id FROM public.skills WHERE name = 'Imagination'), 3.0, 4.0, 4.0, 5.0, 3.8);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Initiative'), (SELECT id FROM public.skills WHERE name = 'Créativité'), 5.0, 4.0, 5.0, 5.0, 4.7);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Initiative'), (SELECT id FROM public.skills WHERE name = 'Innovation'), 8.0, 8.0, 8.0, 7.0, 7.9);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Initiative'), (SELECT id FROM public.skills WHERE name = 'Persévérance'), 9.0, 9.0, 8.0, 8.0, 8.7);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Persévérance'), (SELECT id FROM public.skills WHERE name = 'Imagination'), 2.0, 4.0, 3.0, 6.0, 3.3);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Pitch'), (SELECT id FROM public.skills WHERE name = 'Prise de parole'), 9.0, 9.0, 9.0, 8.0, 8.9);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Pitch'), (SELECT id FROM public.skills WHERE name = 'Argumentation'), 8.0, 10.0, 9.0, 8.0, 8.9);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Pitch'), (SELECT id FROM public.skills WHERE name = 'Analyse'), 6.0, 7.0, 7.0, 8.0, 6.8);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Pitch'), (SELECT id FROM public.skills WHERE name = 'Esprit critique'), 6.0, 7.0, 7.0, 7.0, 6.7);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Prise de parole'), (SELECT id FROM public.skills WHERE name = 'Pitch'), 3.0, 5.0, 4.0, 6.0, 4.2);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Prise de parole'), (SELECT id FROM public.skills WHERE name = 'Argumentation'), 10.0, 10.0, 9.0, 8.0, 9.6);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Prise de parole'), (SELECT id FROM public.skills WHERE name = 'Analyse'), 6.0, 7.0, 7.0, 8.0, 6.8);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Prise de parole'), (SELECT id FROM public.skills WHERE name = 'Esprit critique'), 5.0, 6.0, 7.0, 7.0, 6.0);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Argumentation'), (SELECT id FROM public.skills WHERE name = 'Pitch'), 2.0, 4.0, 3.0, 6.0, 3.3);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Argumentation'), (SELECT id FROM public.skills WHERE name = 'Prise de parole'), 4.0, 6.0, 5.0, 5.0, 5.0);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Argumentation'), (SELECT id FROM public.skills WHERE name = 'Analyse'), 9.0, 9.0, 9.0, 8.0, 8.9);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Argumentation'), (SELECT id FROM public.skills WHERE name = 'Esprit critique'), 9.0, 10.0, 9.0, 8.0, 9.3);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Analyse'), (SELECT id FROM public.skills WHERE name = 'Pitch'), 3.0, 4.0, 5.0, 6.0, 4.1);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Analyse'), (SELECT id FROM public.skills WHERE name = 'Prise de parole'), 4.0, 5.0, 5.0, 6.0, 4.8);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Analyse'), (SELECT id FROM public.skills WHERE name = 'Argumentation'), 6.0, 7.0, 6.0, 7.0, 6.5);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Analyse'), (SELECT id FROM public.skills WHERE name = 'Esprit critique'), 10.0, 10.0, 10.0, 8.0, 9.8);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Esprit critique'), (SELECT id FROM public.skills WHERE name = 'Pitch'), 2.0, 5.0, 4.0, 7.0, 4.0);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Esprit critique'), (SELECT id FROM public.skills WHERE name = 'Prise de parole'), 3.0, 5.0, 5.0, 6.0, 4.4);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Organisation'), (SELECT id FROM public.skills WHERE name = 'Gestion de projet'), NULL, NULL, NULL, NULL, 9.7);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Organisation'), (SELECT id FROM public.skills WHERE name = 'Leadership'), NULL, NULL, NULL, NULL, 7.2);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Organisation'), (SELECT id FROM public.skills WHERE name = 'Résolution de problèmes'), NULL, NULL, NULL, NULL, 7.9);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Gestion de projet'), (SELECT id FROM public.skills WHERE name = 'Organisation'), NULL, NULL, NULL, NULL, 5.1);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Gestion de projet'), (SELECT id FROM public.skills WHERE name = 'Leadership'), NULL, NULL, NULL, NULL, 8.2);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Gestion de projet'), (SELECT id FROM public.skills WHERE name = 'Résolution de problèmes'), NULL, NULL, NULL, NULL, 8.0);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Leadership'), (SELECT id FROM public.skills WHERE name = 'Organisation'), NULL, NULL, NULL, NULL, 4.2);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Leadership'), (SELECT id FROM public.skills WHERE name = 'Gestion de projet'), NULL, NULL, NULL, NULL, 5.5);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Leadership'), (SELECT id FROM public.skills WHERE name = 'Résolution de problèmes'), NULL, NULL, NULL, NULL, 6.2);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Résolution de problèmes'), (SELECT id FROM public.skills WHERE name = 'Organisation'), NULL, NULL, NULL, NULL, 4.9);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Résolution de problèmes'), (SELECT id FROM public.skills WHERE name = 'Gestion de projet'), NULL, NULL, NULL, NULL, 5.8);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Résolution de problèmes'), (SELECT id FROM public.skills WHERE name = 'Leadership'), NULL, NULL, NULL, NULL, 6.6);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Travail d''équipe'), (SELECT id FROM public.skills WHERE name = 'Écoute'), NULL, NULL, NULL, NULL, 9.7);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Travail d''équipe'), (SELECT id FROM public.skills WHERE name = 'Contribution'), NULL, NULL, NULL, NULL, 9.3);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Travail d''équipe'), (SELECT id FROM public.skills WHERE name = 'Autonomie'), NULL, NULL, NULL, NULL, 6.0);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Écoute'), (SELECT id FROM public.skills WHERE name = 'Travail d''équipe'), NULL, NULL, NULL, NULL, 5.7);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Écoute'), (SELECT id FROM public.skills WHERE name = 'Contribution'), NULL, NULL, NULL, NULL, 8.9);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Écoute'), (SELECT id FROM public.skills WHERE name = 'Autonomie'), NULL, NULL, NULL, NULL, 6.0);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Contribution'), (SELECT id FROM public.skills WHERE name = 'Travail d''équipe'), NULL, NULL, NULL, NULL, 5.8);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Contribution'), (SELECT id FROM public.skills WHERE name = 'Écoute'), NULL, NULL, NULL, NULL, 8.9);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Contribution'), (SELECT id FROM public.skills WHERE name = 'Autonomie'), NULL, NULL, NULL, NULL, 7.1);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Autonomie'), (SELECT id FROM public.skills WHERE name = 'Travail d''équipe'), NULL, NULL, NULL, NULL, 6.0);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Autonomie'), (SELECT id FROM public.skills WHERE name = 'Écoute'), NULL, NULL, NULL, NULL, 6.0);
INSERT INTO public.skill_compatibility (skill_a_id, skill_b_id, score_p, score_c, score_t, score_d, total_score) VALUES ((SELECT id FROM public.skills WHERE name = 'Autonomie'), (SELECT id FROM public.skills WHERE name = 'Contribution'), NULL, NULL, NULL, NULL, 7.1);
